export const matchRes = {
    "generated_at": "2022-03-02T22:29:25+00:00",
    "sport_event": {
        "id": "sr:sport_event:22926007",
        "start_time": "2020-08-21T16:00:00+00:00",
        "start_time_confirmed": true,
        "sport_event_context": {
            "sport": {
                "id": "sr:sport:1",
                "name": "Soccer"
            },
            "category": {
                "id": "sr:category:47",
                "name": "Poland",
                "country_code": "POL"
            },
            "competition": {
                "id": "sr:competition:202",
                "name": "Ekstraklasa",
                "gender": "men"
            },
            "season": {
                "id": "sr:season:77453",
                "name": "Ekstraklasa 20\/21",
                "start_date": "2020-08-21",
                "end_date": "2021-05-16",
                "year": "20\/21",
                "competition_id": "sr:competition:202"
            },
            "stage": {
                "order": 1,
                "type": "league",
                "phase": "regular season",
                "start_date": "2020-08-21",
                "end_date": "2021-05-16",
                "year": "20\/21"
            },
            "round": {
                "number": 1
            },
            "groups": [
                {
                    "id": "sr:league:50999",
                    "name": "Ekstraklasa 20\/21"
                }
            ]
        },
        "coverage": {
            "type": "sport_event",
            "sport_event_properties": {
                "lineups": true,
                "extended_player_stats": false,
                "extended_team_stats": false,
                "basic_play_by_play": true,
                "basic_player_stats": true,
                "basic_team_stats": true
            }
        },
        "competitors": [
            {
                "id": "sr:competitor:3113",
                "name": "KGHM Zaglebie Lubin",
                "country": "Poland",
                "country_code": "POL",
                "abbreviation": "ZAG",
                "qualifier": "home",
                "gender": "male"
            },
            {
                "id": "sr:competitor:3121",
                "name": "KKS Lech Poznan",
                "country": "Poland",
                "country_code": "POL",
                "abbreviation": "LPO",
                "qualifier": "away",
                "gender": "male"
            }
        ],
        "venue": {
            "id": "sr:venue:2501",
            "name": "Stadion Zaglebia",
            "capacity": 16068,
            "city_name": "Lubin",
            "country_name": "Poland",
            "map_coordinates": "51.414204,16.197925",
            "country_code": "POL"
        },
        "sport_event_conditions": {
            "ground": {
                "neutral": false
            }
        }
    },
    "sport_event_status": {
        "status": "closed",
        "match_status": "ended",
        "home_score": 2,
        "away_score": 1,
        "winner_id": "sr:competitor:3113",
        "period_scores": [
            {
                "home_score": 0,
                "away_score": 1,
                "type": "regular_period",
                "number": 1
            },
            {
                "home_score": 2,
                "away_score": 0,
                "type": "regular_period",
                "number": 2
            }
        ]
    },
    "lineups": {
        "competitors": [
            {
                "id": "sr:competitor:3121",
                "name": "KKS Lech Poznan",
                "country": "Poland",
                "country_code": "POL",
                "abbreviation": "LPO",
                "qualifier": "away",
                "gender": "male",
                "players": [
                    {
                        "id": "sr:player:138700",
                        "name": "Amorim Pereira Silva, Pedro Miguel",
                        "type": "midfielder",
                        "date_of_birth": "1988-08-31",
                        "nationality": "Portugal",
                        "country_code": "PRT",
                        "height": 182,
                        "weight": 76,
                        "jersey_number": 25,
                        "preferred_foot": "right",
                        "starter": true,
                        "played": true,
                        "order": 6,
                        "position": "central_midfielder"
                    },
                    {
                        "id": "sr:player:139149",
                        "name": "Bednarek, Filip",
                        "type": "goalkeeper",
                        "date_of_birth": "1992-09-26",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 187,
                        "weight": 81,
                        "jersey_number": 35,
                        "preferred_foot": "right",
                        "starter": true,
                        "played": true,
                        "order": 1,
                        "position": "goalkeeper"
                    },
                    {
                        "id": "sr:player:553876",
                        "name": "Crnomarkovic, Djordje",
                        "type": "defender",
                        "date_of_birth": "1993-09-10",
                        "nationality": "Serbia",
                        "country_code": "SRB",
                        "height": 188,
                        "weight": 77,
                        "jersey_number": 5,
                        "preferred_foot": "left",
                        "starter": true,
                        "played": true,
                        "order": 4,
                        "position": "central_defender"
                    },
                    {
                        "id": "sr:player:260085",
                        "name": "Czerwinski, Alan",
                        "type": "defender",
                        "date_of_birth": "1993-02-02",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 181,
                        "weight": 74,
                        "jersey_number": 44,
                        "preferred_foot": "right",
                        "starter": true,
                        "played": true,
                        "order": 2,
                        "position": "right_back"
                    },
                    {
                        "id": "sr:player:114062",
                        "name": "Ishak, Mikael",
                        "type": "forward",
                        "date_of_birth": "1993-03-31",
                        "nationality": "Sweden",
                        "country_code": "SWE",
                        "height": 185,
                        "weight": 81,
                        "jersey_number": 9,
                        "preferred_foot": "both",
                        "place_of_birth": "Stockholm",
                        "starter": true,
                        "played": true,
                        "order": 11,
                        "position": "striker"
                    },
                    {
                        "id": "sr:player:768997",
                        "name": "Jozwiak, Kamil",
                        "type": "midfielder",
                        "date_of_birth": "1998-04-22",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 176,
                        "weight": 70,
                        "jersey_number": 7,
                        "preferred_foot": "right",
                        "starter": true,
                        "played": true,
                        "order": 10,
                        "position": "left_winger"
                    },
                    {
                        "id": "sr:player:1640692",
                        "name": "Kaminski, Jakub",
                        "type": "midfielder",
                        "date_of_birth": "2002-06-05",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 179,
                        "weight": 71,
                        "jersey_number": 38,
                        "preferred_foot": "right",
                        "starter": true,
                        "played": true,
                        "order": 8,
                        "position": "right_winger"
                    },
                    {
                        "id": "sr:player:935220",
                        "name": "Moder, Jakub",
                        "type": "midfielder",
                        "date_of_birth": "1999-04-07",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 188,
                        "weight": 78,
                        "jersey_number": 15,
                        "preferred_foot": "right",
                        "starter": true,
                        "played": true,
                        "order": 7,
                        "position": "central_midfielder"
                    },
                    {
                        "id": "sr:player:935188",
                        "name": "Puchacz, Tymoteusz",
                        "type": "defender",
                        "date_of_birth": "1999-01-23",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 180,
                        "weight": 74,
                        "jersey_number": 27,
                        "place_of_birth": "Zielona Gora",
                        "starter": true,
                        "played": true,
                        "order": 5,
                        "position": "left_back"
                    },
                    {
                        "id": "sr:player:1281348",
                        "name": "Ramirez Fernandez, Daniel",
                        "type": "midfielder",
                        "date_of_birth": "1992-06-18",
                        "nationality": "Spain",
                        "country_code": "ESP",
                        "height": 175,
                        "weight": 70,
                        "jersey_number": 10,
                        "preferred_foot": "both",
                        "starter": true,
                        "played": true,
                        "order": 9,
                        "position": "central_midfielder"
                    },
                    {
                        "id": "sr:player:187231",
                        "name": "Satka, Lubomir",
                        "type": "defender",
                        "date_of_birth": "1995-12-02",
                        "nationality": "Slovakia",
                        "country_code": "SVK",
                        "height": 188,
                        "weight": 78,
                        "jersey_number": 37,
                        "preferred_foot": "right",
                        "starter": true,
                        "played": true,
                        "order": 3,
                        "position": "central_defender"
                    },
                    {
                        "id": "sr:player:353960",
                        "name": "Dejewski, Tomasz",
                        "type": "defender",
                        "date_of_birth": "1995-04-22",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 191,
                        "weight": 82,
                        "jersey_number": 13,
                        "preferred_foot": "right"
                    },
                    {
                        "id": "sr:player:820376",
                        "name": "Gumny, Robert",
                        "type": "defender",
                        "date_of_birth": "1998-06-04",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 177,
                        "weight": 61,
                        "jersey_number": 2,
                        "preferred_foot": "right",
                        "place_of_birth": "Poznan"
                    },
                    {
                        "id": "sr:player:149673",
                        "name": "Malenica, Marko",
                        "type": "goalkeeper",
                        "date_of_birth": "1994-02-08",
                        "nationality": "Croatia",
                        "country_code": "HRV",
                        "height": 192,
                        "weight": 84,
                        "jersey_number": 33,
                        "preferred_foot": "right"
                    },
                    {
                        "id": "sr:player:1640696",
                        "name": "Marchwinski, Filip",
                        "type": "midfielder",
                        "date_of_birth": "2002-01-10",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 185,
                        "weight": 72,
                        "jersey_number": 11,
                        "preferred_foot": "both",
                        "played": true
                    },
                    {
                        "id": "sr:player:883094",
                        "name": "Muhar, Karlo",
                        "type": "midfielder",
                        "date_of_birth": "1996-01-17",
                        "nationality": "Croatia",
                        "country_code": "HRV",
                        "height": 188,
                        "weight": 83,
                        "jersey_number": 6
                    },
                    {
                        "id": "sr:player:1640688",
                        "name": "Niewiadomski, Jakub",
                        "type": "defender",
                        "date_of_birth": "2002-04-09",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 183,
                        "jersey_number": 40,
                        "preferred_foot": "left"
                    },
                    {
                        "id": "sr:player:28394",
                        "name": "Rogne, Thomas Pauck",
                        "type": "defender",
                        "date_of_birth": "1990-06-29",
                        "nationality": "Norway",
                        "country_code": "NOR",
                        "height": 185,
                        "weight": 86,
                        "jersey_number": 4,
                        "preferred_foot": "right"
                    },
                    {
                        "id": "sr:player:1091640",
                        "name": "Skoras, Michal",
                        "type": "midfielder",
                        "date_of_birth": "2000-02-15",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 172,
                        "weight": 64,
                        "jersey_number": 21,
                        "preferred_foot": "right",
                        "played": true
                    },
                    {
                        "id": "sr:player:1640706",
                        "name": "Szymczak, Filip",
                        "type": "forward",
                        "date_of_birth": "2002-05-06",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 184,
                        "jersey_number": 23,
                        "preferred_foot": "left",
                        "played": true
                    }
                ],
                "jersey": {
                    "type": "home",
                    "base": "0037ff",
                    "sleeve": "0040ff",
                    "number": "b2af5c",
                    "squares": false,
                    "stripes": false,
                    "horizontal_stripes": false,
                    "split": false,
                    "shirt_type": "short_sleeves",
                    "sleeve_detail": "001eff"
                }
            },
            {
                "id": "sr:competitor:3113",
                "name": "KGHM Zaglebie Lubin",
                "country": "Poland",
                "country_code": "POL",
                "abbreviation": "ZAG",
                "qualifier": "home",
                "gender": "male",
                "players": [
                    {
                        "id": "sr:player:57463",
                        "name": "Balic, Sasa",
                        "type": "defender",
                        "date_of_birth": "1990-01-29",
                        "nationality": "Montenegro",
                        "country_code": "MNE",
                        "height": 185,
                        "weight": 78,
                        "jersey_number": 3,
                        "preferred_foot": "left",
                        "starter": true,
                        "played": true,
                        "order": 5,
                        "position": "left_back"
                    },
                    {
                        "id": "sr:player:80988",
                        "name": "Bashkirov, Evgeni",
                        "type": "midfielder",
                        "date_of_birth": "1991-07-06",
                        "nationality": "Russian federation",
                        "country_code": "RUS",
                        "height": 175,
                        "weight": 71,
                        "jersey_number": 4,
                        "preferred_foot": "both",
                        "starter": true,
                        "played": true,
                        "order": 7,
                        "position": "central_midfielder"
                    },
                    {
                        "id": "sr:player:75509",
                        "name": "Bohar, Damjan",
                        "type": "forward",
                        "date_of_birth": "1991-10-18",
                        "nationality": "Slovenia",
                        "country_code": "SVN",
                        "height": 172,
                        "weight": 69,
                        "jersey_number": 39,
                        "starter": true,
                        "played": true,
                        "order": 8,
                        "position": "right_winger"
                    },
                    {
                        "id": "sr:player:935230",
                        "name": "Chodyna, Kacper",
                        "type": "midfielder",
                        "date_of_birth": "1999-05-24",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 176,
                        "weight": 68,
                        "jersey_number": 26,
                        "starter": true,
                        "played": true,
                        "order": 2,
                        "position": "right_back"
                    },
                    {
                        "id": "sr:player:57980",
                        "name": "Guldan, Lubomir",
                        "type": "defender",
                        "date_of_birth": "1983-01-30",
                        "nationality": "Slovakia",
                        "country_code": "SVK",
                        "height": 183,
                        "weight": 82,
                        "jersey_number": 33,
                        "preferred_foot": "right",
                        "starter": true,
                        "played": true,
                        "order": 4,
                        "position": "central_defender"
                    },
                    {
                        "id": "sr:player:335907",
                        "name": "Hladun, Dominik",
                        "type": "goalkeeper",
                        "date_of_birth": "1995-09-17",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 190,
                        "weight": 77,
                        "jersey_number": 30,
                        "preferred_foot": "right",
                        "starter": true,
                        "played": true,
                        "order": 1,
                        "position": "goalkeeper"
                    },
                    {
                        "id": "sr:player:1122899",
                        "name": "Jonczy, Dominik",
                        "type": "defender",
                        "date_of_birth": "1997-05-17",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 189,
                        "weight": 83,
                        "jersey_number": 27,
                        "starter": true,
                        "played": true,
                        "order": 3,
                        "position": "central_defender"
                    },
                    {
                        "id": "sr:player:354576",
                        "name": "Mraz, Samuel",
                        "type": "forward",
                        "date_of_birth": "1997-05-13",
                        "nationality": "Slovakia",
                        "country_code": "SVK",
                        "height": 184,
                        "weight": 78,
                        "jersey_number": 11,
                        "place_of_birth": "Malacky",
                        "starter": true,
                        "played": true,
                        "order": 11,
                        "position": "striker"
                    },
                    {
                        "id": "sr:player:174053",
                        "name": "Starzynski, Filip",
                        "type": "midfielder",
                        "date_of_birth": "1991-05-27",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 184,
                        "weight": 70,
                        "jersey_number": 18,
                        "preferred_foot": "right",
                        "starter": true,
                        "played": true,
                        "order": 9,
                        "position": "central_midfielder"
                    },
                    {
                        "id": "sr:player:78888",
                        "name": "Zivec, Sasa Aleksander",
                        "type": "midfielder",
                        "date_of_birth": "1991-04-02",
                        "nationality": "Slovenia",
                        "country_code": "SVN",
                        "height": 178,
                        "weight": 70,
                        "jersey_number": 7,
                        "preferred_foot": "both",
                        "starter": true,
                        "played": true,
                        "order": 10,
                        "position": "left_winger"
                    },
                    {
                        "id": "sr:player:1011409",
                        "name": "Zubrowski, Jakub",
                        "type": "midfielder",
                        "date_of_birth": "1992-03-21",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 181,
                        "weight": 73,
                        "jersey_number": 14,
                        "preferred_foot": "right",
                        "starter": true,
                        "played": true,
                        "order": 6,
                        "position": "central_midfielder"
                    },
                    {
                        "id": "sr:player:1604660",
                        "name": "Bartolewski, Mateusz",
                        "type": "defender",
                        "date_of_birth": "1998-01-12",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 187,
                        "weight": 76,
                        "jersey_number": 77
                    },
                    {
                        "id": "sr:player:72265",
                        "name": "Forenc, Konrad",
                        "type": "goalkeeper",
                        "date_of_birth": "1992-07-17",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 191,
                        "weight": 91,
                        "jersey_number": 12
                    },
                    {
                        "id": "sr:player:1543521",
                        "name": "Poreba, Lukasz",
                        "type": "midfielder",
                        "date_of_birth": "2000-03-13",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 180,
                        "weight": 70,
                        "jersey_number": 8,
                        "preferred_foot": "right",
                        "played": true
                    },
                    {
                        "id": "sr:player:167467",
                        "name": "Reese, Soren",
                        "type": "defender",
                        "date_of_birth": "1993-07-29",
                        "nationality": "Denmark",
                        "country_code": "DNK",
                        "height": 186,
                        "weight": 71,
                        "jersey_number": 6,
                        "preferred_foot": "left"
                    },
                    {
                        "id": "sr:player:754348",
                        "name": "Simic, Lorenco",
                        "type": "defender",
                        "date_of_birth": "1996-07-15",
                        "nationality": "Croatia",
                        "country_code": "HRV",
                        "height": 195,
                        "weight": 73,
                        "jersey_number": 5,
                        "preferred_foot": "right",
                        "place_of_birth": "Split",
                        "played": true
                    },
                    {
                        "id": "sr:player:96557",
                        "name": "Sirk, Rok",
                        "type": "forward",
                        "date_of_birth": "1993-09-10",
                        "nationality": "Slovenia",
                        "country_code": "SVN",
                        "height": 184,
                        "weight": 74,
                        "jersey_number": 9,
                        "played": true
                    },
                    {
                        "id": "sr:player:1595780",
                        "name": "Sypek, Jakub",
                        "type": "midfielder",
                        "date_of_birth": "2001-04-07",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 180,
                        "weight": 72,
                        "jersey_number": 20
                    },
                    {
                        "id": "sr:player:962811",
                        "name": "Szysz, Patryk",
                        "type": "forward",
                        "date_of_birth": "1998-04-01",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 177,
                        "weight": 70,
                        "jersey_number": 17,
                        "played": true
                    },
                    {
                        "id": "sr:player:140662",
                        "name": "Wojcicki, Jakub",
                        "type": "defender",
                        "date_of_birth": "1988-07-09",
                        "nationality": "Poland",
                        "country_code": "POL",
                        "height": 190,
                        "weight": 80,
                        "jersey_number": 23,
                        "preferred_foot": "right"
                    }
                ],
                "jersey": {
                    "type": "home",
                    "base": "000000",
                    "sleeve": "000000",
                    "number": "ada57e",
                    "squares": false,
                    "stripes": false,
                    "horizontal_stripes": false,
                    "split": false,
                    "shirt_type": "short_sleeves"
                }
            }
        ]
    }
}